### PR TITLE
Math-Magicians: Full website

### PR DESCRIPTION
**Pull request by Kamba56**
- Created a website consisting of 3 pages: Home, Calculator, and Quote.
- Added styling to improve the look and feel.
- Created a route for every page.
- Made sure that navigation links for all 3 routes are displayed on each page.
- Used [React Router](https://reactrouter.com/) to make the routes work.

### CODE REVIEW

**Review by zieeco — CHANGES_REQUESTED** [review]
Hi @Kamba56 ,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments below:_

- [ ] Please, kindly update your MIT.md link, make sure it's not a broken link to make your readme more professional.





## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kamba56** [comment]
@zieeco Thank you for your review.

**Review by descholar-ceo — APPROVED** [review]
Hi @Kamba56 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Fixed the license link ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kamba56** [comment]
@descholar-ceo  Thank you for your review

**Pull request merged**
